[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm@8 --silent", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm db:generate", "pnpm --filter api build"]

[start]
cmd = "node apps/api/dist/main.js"
